### ISSUE TITLE
Missing imported games

### ISSUE THREAD

**Issue by mpm11011** [mpm11011/galaxy-integration-rpcs3#8]
Ratchet and Clank and Modern Warfare 2, were 2 games that the plugin discovered and imported, but then some weird things happened.

- Galaxy couldn't recognize them so no icons, descriptions, etc were listed.
- I edited the titles thinking it would get Galaxy to recognize them.
- After a day or two, these games disappeared from my library and I don't see a way to get them back, even after removing and re-adding the plugin. 

Galaxy problem or plugin problem, I do not know.

**Comment by mpm11011** [comment]
Found a clue form the GalaxyClient.log file:

`2019-09-16 17:32:17.393 [Warning][ (0)] [TID 3080][galaxy_client]: GamesDbPiecesPullerByRelease retrieved response code 404, will treat game 'vision_BLUS30377' pieces as not set.
2019-09-16 17:32:17.393 [Information][ (0)] [TID 11996][galaxy_client]: Sending problem report of type GamesDb-Request-Error: {"Arguments":{"applicationType":"GOG Galaxy","clientVersion":"2.0.5.138","detectedOsVersion":"win10","os":"windows","osIdentification":"windows: Windows 10 10.0 (Build 18362)","productId":"vision_BLUS30377","returnCode":404,"updateChannel":""},"ProblemReport":"GamesDb-Request-Error"}
2019-09-16 17:32:17.393 [Warning][ (0)] [TID 3080][galaxy_client]: GamesDbPiecesPullerByRelease retrieved response code 404, will treat game 'vision_NPUA80643' pieces as not set.
2019-09-16 17:32:17.393 [Information][ (0)] [TID 3080][galaxy_client]: Discarding problem report because 0s elapsed since last sending of GamesDb-Request-Error problem.`

These are the Game ID's for MW2 and R&C. 

Another piece of information:

`2019-09-15 14:15:24.921 [Information][ (0)] [TID 11124][galaxy_client]: Sending problem report of type GamesDb-Request-Error: {"Arguments":{"applicationType":"GOG Galaxy","clientVersion":"2.0.5.138","detectedOsVersion":"win10","os":"windows","osIdentification":"windows: Windows 10 10.0 (Build 18362)","productId":"vision_NPUA80643","returnCode":404,"updateChannel":""},"ProblemReport":"GamesDb-Request-Error"}`

So it seems that, after messing with the release date (which for those 2 titles was "Invalid date ()") Galaxy's backend can no longer properly query for the games, and so they won't be showed in the front end.

I'll submit a bug report with GOG and see what they say.

**Comment by TBemme** [comment]
From my own tests and comments I've seen from GOG staff (so this only guesses/assumptions, not neccessarily what is happening) - this happens when a game fails to automatically find a "match" in the gamesdb. Because the id (and platform) can be anything, I think the match is performed based on the game_title that the plugin provides.

Games that don't automatically get matched have to wait for a staff member to do so manually. That can take a while, or other things can go wrong (if it is incorrectly marked as a DLC or spam, Galaxy will never show the game).

That first id in the database appears to have been marked as spam: https://gamesdb.gog.com/platforms/vision/external_releases/NPUA80643

Plugins/users can't fix this unfortunately, only the staff can if you report it. That has happened to a couple of games I've tried to add with my plugins.

**Comment by mpm11011** [comment]
Thanks for the heads up! I'm surprised they have functionality to list games as spam. 

I'll change the status of this issue and close it, since it seems to be unrelated to the plugin or API.
